benchmark_suffix: test_benchmark_bohb_save_models
experiment_name: benchmark_test
backbone:
  backbone: prithvi_swin_B
tasks:
  # - name: agb
  #   type: regression
  #   loss: rmse
  #   bands:
  #     - BLUE
  #     - GREEN
  #     - RED
  #     - NIR_NARROW
  #     - SWIR_1
  #     - SWIR_2
  #   ignore_index: -1
  #   backbone_args:
  #     drop_path_rate: 0.3
  #   max_epochs: 1
  #   head_args:
  #     final_act: torch.nn.ReLU
  #     learned_upscale_layers: 2
  #   datamodule: benchmark/resources/dataset_specifications/agb.yaml
  #   decoder: FCNDecoder
  #   metric: val/RMSE
  - name: sen1floods11
    type: segmentation
    loss: ce
    ignore_index: -1
    lr: 10
    bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    max_epochs: 2
    datamodule: benchmark/resources/dataset_specifications/sen1floods11.yaml
    decoder: FCNDecoder
    metric: val/loss
    early_prune: false
  - name: eurosat
    type: classification
    loss: ce
    bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    num_classes: 10
    max_epochs: 2
    datamodule: benchmark/resources/dataset_specifications/eurosat.yaml
    decoder: IdentityDecoder
    metric: val/loss
    early_prune: true
  # optimization_except:
  #   - decoder_channels
  #   - head_dropout
  # - decoder
n_trials: 2
save_models: True
storage_uri: /dccstor/geofm-finetuning/carlosgomes/benchmark/
ray_storage_path: /dccstor/geofm-finetuning/carlosgomes/ray_storage
optimization_space:
  # decoder:
  #   - FCNDecoder
  #   - UperNetDecoder
  lr:
    min: 1e-6
    max: 1e-3
    type: real
    log: true
  batch_size:
    - 2
    - 4
    - 8
    # - 32
    # - 64
  # decoder_channels:
  #   - 32
  #   - 64
  #   - 128
  # head_dropout:
  #   min: 0
  #   max: 0.8
  #   type: real
  freeze_backbone:
    - true
    - false
