site_name: Benchmark
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folde
          options:
            show_root_heading: true

repo_url: https://github.ibm.com/GeoFM-Finetuning/benchmark
nav:
  - index.md
  - mlflow.md
  - new_backbone.md
  - ray.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
