# configuration approach followed:
# - whenever possible, prefer pyproject.toml
# - for configurations insufficiently supported by pyproject.toml, use setup.cfg instead
# - setup.py discouraged; minimal stub included only for compatibility with legacy tools

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["benchmark*"]

[project]

name = "terratorch-iterate"
version = "0.1.0"
description = "A tool for benchmarking and hpo"
authors = [
      { name = "Carlos Gomes", email = "carlos.gomes@ibm.com" },
      { name = "Naomi Simumba"},
      { name = "Francesc Marti Escofet"},
      { name = "Daniela Szwarcman"},
      { name = "Leonardo Pondian Tizzei"},
      { name = "Romeo Kienzler"} 
]
license = { "text" = "Apache License, Version 2.0" }
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
]
readme = "README.md"

dependencies = [
"click",
# optional dependencies that can be opted in by apps.
"torchvision>=0.17.0",
"terratorch>=0.99.8", 

# requests>=2.32.0 because of this vulnerability https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56
"requests>=2.32.0",
# Jinja2 vulnerability issue https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj
"Jinja2>=3.1.5",
# urllib3 vulnerability issue https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf
"urllib3>=2.2.2",
# fix this sqlparse issue https://www.cve.org/CVERecord?id=CVE-2024-4340
"sqlparse>=0.5.0",
# fix this scikit-learn issue https://www.cve.org/CVERecord?id=CVE-2024-5206
"scikit-learn>=1.5.0",
# fix this pillow issue https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security
"pillow>=10.3.0",
# fix this aiohttp issue https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g
"aiohttp>=3.9.4",
# fix this tqdm issue https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p
"tqdm>=4.66.3",
# fix this werkzeug issue https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985
"werkzeug>=3.0.3",
# fix this pytorch-lightning issue https://nvd.nist.gov/vuln/detail/CVE-2024-5452
"pytorch-lightning>=2.3.3",
"more-itertools~=10.2.0", 
"importlib-metadata~=4.13.0",
"numpy~=1.26.0",
"optuna~=3.5.0",
"tabulate~=0.9.0",
"types-tabulate~=0.9.0.20240106",
"ray~=2.37.0",
"gputil~=1.4.0",
"asyncio~=3.4.3",
"opencv-python-headless~=4.9.0.80",
"hpbandster~=0.7.4",
"configspace~=0.7.1",
"optuna-integration~=3.6.0",
"seaborn~=0.13.2",
"geobench"
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8", 
  "mkdocs-material",
  "mkdocstrings[python]",
  "mike" # for building docs with versions
]

test = [
  "coverage",
  "pytest",
  "pytest-cov"
]

[tool.black]
target-version = ["py310"]
line-length = 88
skip-string-normalization = true

[project.scripts]
benchmark = "benchmark.backbone_benchmark:main"
ray_benchmark = "benchmark.benchmark_ray:main"
repeat_experiments = "benchmark.repeat_best_experiment:main"


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
force_to_top = ["rdkit", "scikit-learn"]

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--cov=benchmark --cov-report html"