experiment_name: dofa_large_patch16_224_upernetdecoder_true_modified
defaults:
  trainer_args:
    max_epochs: 2
    precision: bf16-mixed
    log_every_n_steps: 1
  terratorch_task:
    model_args:
      backbone_pretrained: True
      backbone: dofa_large_patch16_224
      backbone_out_indices:
        - 5
        - 11
        - 17
        - 23
    model_factory: EncoderDecoderFactory
    optimizer: AdamW
tasks:
  - name: nz_cattle
    type: segmentation
    direction: max
    metric: val/Multiclass_Jaccard_Index
    early_stop_patience: 5
    terratorch_task:
      loss: ce
      model_args:
        backbone_model_bands:
          - RED
          - GREEN
          - BLUE
        num_classes: 2
        decoder: UperNetDecoder
        decoder_channels: 128
        decoder_scale_modules: true
        necks:
        - name: ReshapeTokensToImage
    datamodule:
      class_path: terratorch.datamodules.MNzCattleNonGeoDataModule
      init_args:
        partition: "0.01x_train"
        train_transform:
          - class_path: albumentations.HorizontalFlip
            init_args:
              p: 0.5
          - class_path: albumentations.VerticalFlip
            init_args:
              p: 0.5
          - class_path: albumentations.Resize
            init_args:
              height: 224
              width: 224
          - class_path: ToTensorV2
        val_transform:
          - class_path: albumentations.Resize
            init_args:
              height: 224
              width: 224
          - class_path: ToTensorV2
        test_transform:
          - class_path: albumentations.Resize
            init_args:
              height: 224
              width: 224
          - class_path: ToTensorV2
        batch_size: 16
        num_workers: 4
        data_root: "/dccstor/geofm-finetuning/datasets/geobench/segmentation_v1.0"
        bands:
          - "RED"
          - "GREEN"
          - "BLUE"
n_trials: 1
save_models: False
storage_uri: /dccstor/geofm-finetuning/terratorch-iterate-test
ray_storage_path: /dccstor/geofm-finetuning/terratorch-iterate-test/ray_storage
optimization_space:
  batch_size:
    - 8
    - 16
    - 32
  lr:
    min: 6e-5
    max: 1e-3
    type: real
    log: true
  optimizer_hparams:
    weight_decay:
      min: 0
      max: 0.4
      type: real
  model_args:
    decoder_channels:
      - 64
      - 128
      - 256
      - 512
run_repetitions: 1
