class_path: terratorch.datamodules.TorchNonGeoDataModule
init_args:
  transforms:
    # a possible way to select bands:
    # - class_path: SelectBands
    #   init_args:
    #     band_indices:
    #       - 2
    #       - 1
    #       - 0
    - class_path: albumentations.augmentations.geometric.resize.Resize
      dict_kwargs:
        height: 224
        width: 224
    - class_path: ToTensorV2
  cls: torchgeo.datamodules.EuroSATDataModule
  batch_size: 32
  num_workers: 8
dict_kwargs:
  root: /dccstor/geofm-pre/EuroSat
  download: True
  bands:
    - B02
    - B03
    - B04
    - B08A
    - B11
    - B12
