class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
init_args:
  batch_size: 4
  num_workers: 8
  dataset_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
  output_bands:
    - BLUE
    - GREEN
    - RED
    - NIR_NARROW
    - SWIR_1
    - SWIR_2
  rgb_indices:
    - 2
    - 1
    - 0
  train_transform:
    - class_path: albumentations.RandomCrop
      init_args:
        height: 224
        width: 224
    - class_path: albumentations.HorizontalFlip
      init_args:
        p: 0.5
    - class_path: ToTensorV2
  no_data_replace: 0
  no_label_replace: -1
  train_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/training
  train_label_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/training
  val_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/validation
  val_label_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/validation
  test_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/validation
  test_label_data_root: /dccstor/geofm-finetuning/fire-scars/finetune-data/6_bands_no_replant_extended/validation
  img_grep: "*_merged.tif"
  label_grep: "*.mask.tif"
  means:
    - 0.033349706741586264
    - 0.05701185520536176
    - 0.05889748132001316
    - 0.2323245113436119
    - 0.1972854853760658
    - 0.11944914225186566
  stds:
    - 0.02269135568823774
    - 0.026807560223070237
    - 0.04004109844362779
    - 0.07791732423672691
    - 0.08708738838140137
    - 0.07241979477437814
  num_classes: 2
